# Set up the prompt
fpath=( "$HOME/.zfunctions" $fpath )
PS1=' ; '

# Colours please
export TERM=xterm-256color

# set key repeat for debian
if (( $+xset )) ; then
  xset r rate 180 40
fi

### iTerm2 Titleback One Dark theme
# echo -e "\033]6;1;bg;red;brightness;40\a"
# echo -e "\033]6;1;bg;green;brightness;44\a"
# echo -e "\033]6;1;bg;blue;brightness;52\a"
# clear

### Custom bins
export PATH="$HOME/bin:$PATH"
### Debian path
export PATH="/usr/bin:$PATH"
### Homebrew path 🍺
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$PATH"
### Rust path 🦀
export PATH="$HOME/.cargo/bin:$PATH"
### Go path
export PATH="/opt/go/bin:$PATH"
export GOPATH="$HOME/go"
### Luarocks path
export PATH="$HOME/.luarocks/bin:$PATH"
export PATH="/home/rain/.asdf/installs/luaJIT/2.0.5--2.4.4/bin:$PATH"

### history file config
HISTFILE=~/.zsh_history
HISTSIZE=999999999
SAVEHIST=$HISTSIZE
setopt APPEND_HISTORY

### better tab completion
autoload -U compinit
compinit
# case insensitive
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

### zsh autosuggestions
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

### up or down history based on what's typed in already
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

### some aliases
alias cl='clear'
alias ls='ls -GFh'
alias diff='git diff --no-index'

### jump to recently used items
eval "$(fasd --init zsh-hook zsh-ccomp zsh-ccomp-install zsh-wcomp zsh-wcomp-install)"
function fasd_cd() {
  if [ $# -le 1 ]; then
    fasd "$@"
  else
    local _fasd_ret="$(fasd -e 'printf %s' "$@")"
    [ -z "$_fasd_ret" ] && return
    [ -d "$_fasd_ret" ] && cd "$_fasd_ret" || printf %s\\n "$_fasd_ret"
  fi
}
alias z='fasd_cd -d' # cd, same functionality as j in autojump

### Sublime
export PATH=/Applications/Sublime\ Text.app/Contents/SharedSupport/bin:$PATH

alias vim="nvim"
alias vi="nvim"
export EDITOR="nvim"
export REACT_EDITOR="subl"

# v [path]
# Opens the passed path or the current dir in vi
function v () {
    # if there's no argument
    if [ $# -eq 0 ]; then
        vi ./
        return
    fi
    vi $@
}

# zv [name]
# Uses fasd to search for a likely folder and opens it with vi
function zv () {
    v $(fasd -e 'printf %s' "$@");
}

### git
alias gaa='git add -A'
alias gs='git status'
alias gcm='git commit -m'
alias gca='git commit --amend --no-edit'
alias gce='git commit --amend'
alias gco='git checkout'
alias gd='git diff --ignore-space-at-eol --ignore-space-change --ignore-all-space --ignore-blank-lines'
alias glg="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --"
alias gpp='git pull --rebase && git push'

# git recent
git config --global alias.recent 'branch --sort=-committerdate --format="%(committerdate:relative)%09%(refname:short)"'

### nvm
if [ -d ~/.nvm ]; then
  export NVM_DIR="$HOME/.nvm"
  [ -f "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"
fi

### rbenv
if [ -d ~/.rbenv ]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi

# added by travis gem
[ -f ~/.travis/travis.sh ] && source ~/.travis/travis.sh

# fzf fuzzy completion
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS='--color=bw'

alias du='ncdu --color dark -rr -x --exclude .git --exclude node_modules'

# Local config
for file in ~/.config/localconfig/*(N); do
  source "$file"
done

### source asdf vm manager
[ -f ~/.asdf/asdf.sh ] && source ~/.asdf/asdf.sh
[ -f /usr/local/opt/asdf/asdf.sh ] && source /usr/local/opt/asdf/asdf.sh

[ -f /home/linuxbrew/.linuxbrew/bin/brew ] && \
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

func w () {
  yarn workspace @treasure-data/$@
};

### zsh syntax highlighting - Must be last
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


# bun completions
[ -s "~/.bun/_bun" ] && source "~/.bun/_bun"

# Bun
export BUN_INSTALL="~/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
