# Set up the prompt``
PS1=' ; '

# Colours please
export TERM=xterm-256color

# set key repeat for debian
if (( $+xset )) ; then
  xset r rate 180 40
fi

# Set PATH, MANPATH, etc., for Homebrew.
[ -f /opt/homebrew/bin/brew ] && \
	eval "$(/opt/homebrew/bin/brew shellenv)"

[ -f /home/linuxbrew/.linuxbrew/bin/brew ] && \
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

[ -f /home/linuxbrew/.linuxbrew/bin/brew ] && \
	export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"

### Custom bins
export PATH="$HOME/bin:$PATH"
### Debian path
export PATH="/usr/bin:$PATH"
### Homebrew path 🍺
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$PATH"
### Rust path 🦀
export PATH="$HOME/.cargo/bin:$PATH"
### Go path
export PATH="/opt/go/bin:$PATH"
export GOPATH="$HOME/go"

### history file config
HISTFILE=~/.zsh_history
HISTSIZE=999999999
HISTFILESIZE=$HISTSIZE
SAVEHIST=$HISTSIZE
setopt APPEND_HISTORY
alias history="history 1"

### better tab completion
autoload -U compinit
compinit
# case insensitive
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

### up or down history based on what's typed in already
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

### some aliases
alias cl='clear'
alias ls='ls -GFh'
alias diff='git diff --no-index'

alias vim="nvim"
alias vi="nvim"
export EDITOR="code"
export REACT_EDITOR="code"

# v [path]
# Opens the passed path or the current dir in vi
function v () {
    # if there's no argument
    if [ $# -eq 0 ]; then
        vi ./
        return
    fi
    vi $@
}

### jump to recently used items
eval "$(fasd --init zsh-hook zsh-ccomp zsh-ccomp-install zsh-wcomp zsh-wcomp-install)"
function fasd_cd() {
  if [ $# -le 1 ]; then
    fasd "$@"
  else
    local _fasd_ret="$(fasd -e 'printf %s' "$@")"
    [ -z "$_fasd_ret" ] && return
    [ -d "$_fasd_ret" ] && cd "$_fasd_ret" || printf %s\\n "$_fasd_ret"
  fi
}
alias z='fasd_cd -d' # cd, same functionality as j in autojump

function trash() {
  echo "[x] moving files to trash..."
  mv "$@" "$HOME/.trash"
}

### git
alias gaa='git add -A'
alias gs='git status'
alias gcm='git commit -m'

# fzf fuzzy completion
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS='--color=bw'

alias disk-use='ncdu --color dark -rr -x --exclude .git --exclude node_modules'

# bun completions
[ -f ~/.bun/_bun ] && source ~/.bun/_bun

# Bun
export BUN_INSTALL="~/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# export NODE_OPTIONS=--max_old_space_size=12288

[ -f ~/.env ] && source ~/.env

export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
